name: Auto Summarize Post
on:
  push:
    paths:
    - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install requests
    - name: Get list of changed files
      id: getfile
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV
    - name: Run summarization script
      run: python summarize_post.py ${{ steps.getfile.outputs.files }}